openapi: 3.0.1
info:
  title: Stock2 API
  version: "v1"
  description: "Stock2のAPI仕様書"

servers:
  - url: http://localhost:3000
    description: 開発環境
  - url: https://api.example.com
    description: 本番環境

components:
  securitySchemes:
    Bearer:
      type: http
      scheme: bearer
      bearerFormat: JWT
